### ISSUE TITLE
Included library

### ISSUE THREAD

**Issue by sanfernoronha** [kad99kev/SEM-4#1]
Change to #include<GL/glut.h>

**Comment by kad99kev** [comment]
> Change to #include<GL/glut.h>

You're not wrong, but for the IDE I'm using the header files are automatically included. You have to mention this line during the practicals tho. Plus I think the #include<GLUT/glut.h> has got more to do with Apple than the IDE itself.

**Comment by sanfernoronha** [comment]
It wasn't running on linux that's all. If it's running on a mac then cool.
